# Generated by Django 4.1 on 2022-09-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('brand', models.CharField(max_length=999)),
                ('retail_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=9999)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
